map_update_interval: 0.1 
temporalUpdate: 0.1
xmin: -4.0
xmax:  4.0
ymin: -4.0
ymax:  4.0

srr: 0.001
srt: 0.001
str: 0.001
stt: 0.001


transform_publish_period: 0.1
throttle_scans: 1
maxUrange: 3.8
maxRange: 6.5


sigma: 0.0000000001
kernelSize: 1
