scan_filter_chain:
- name: angle1
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.15
    upper_angle: -1.57
- name: angle2
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: 1.57
    upper_angle: 3.15
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.5
    upper_threshold: 4.0
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1
