obstacle_range: 1.8
raytrace_range: 2
footprint: [[-0.64, -0.3825], [-0.64, 0.3825], [0.38, 0.3825], [0.38, -0.3825]]
#robot_radius: ir_of_robot
inflation_radius: 1.2
 

  #sensor_frame: dtw_robot1/front_laser_link
  #topic: /dtw_robot1/front_laser/scan
observation_sources: laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, marking: true, clearing: true, inf_is_valid: true}
 

