global_costmap:
  #global_frame: dtw_robot1/map
  #robot_base_frame: dtw_robot1/base_link
  update_frequency: 4.0
  static_map: true

  publish_frequency: 3.0
  inflation_radius: 1.0
  width: 30.0
  height: 30.0
  rolling_window: false
  transform_tolerance: 1.0

