local_costmap:
  #global_frame: dtw_robot1/odom
  #robot_base_frame: dtw_robot1/base_link
  update_frequency: 4.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  meter_scoring: true
